name: siot_driver_pro
description: A new Flutter project.
publish_to: 'none'
#version: 2.0.7+22
version: 1.0.0+6


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  keyboard_actions: ^4.2.1
  http: ^1.2.2
  flutter_blue_plus: ^1.35.3
  location: ^7.0.0
  geolocator: ^13.0.2
  hive_flutter: ^1.1.0
  flutter_xlider: ^3.0.1
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2
  #intl: 0.19.0
  common_utils: ^2.1.0
  table_calendar: ^3.1.2
  pdf: ^3.11.1
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.4
  permission_handler: ^11.3.1
  open_file: ^3.5.11
  flutter_foreground_task: ^6.1.2

dependency_overrides:
  win32: 5.5.4
  archive: 3.6.1

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#FFFFFF"
  image: "assets/images/login/logo_light.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/images/login/logo_dark.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/order/
    - assets/images/goods/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/stats/
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf