name: siot_driver_pro
description: A new Flutter project.
publish_to: 'none'

#version: 2.0.7+22
version: 1.0.0+16

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI
  keyboard_actions: ^4.2.1
  flutter_xlider: ^3.0.1
  table_calendar: ^3.1.2

  # Network
  http: ^1.2.2

  # Bluetooth
  flutter_blue_plus: ^1.35.5

  # Location
  location: ^7.0.1
  geolocator: ^13.0.2

  # Storage
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Permissions
  permission_handler: ^11.4.0

  # PDF
  pdf: ^3.11.1
  open_file: ^3.5.11

  # Utils
  intl: ^0.19.0
  common_utils: ^2.1.0

  # Splash
  flutter_native_splash: ^2.4.4

  # Foreground service
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#FFFFFF"
  image: assets/images/login/logo_light.png

flutter_icons:
  android: true
  image_path: assets/images/login/logo_dark.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/order/
    - assets/images/goods/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/stats/

  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf








